type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: true
loaderthreads: 1
terminals: 1
works:
    work:
        time_secs: 10
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal2
    properties:
        # Goal2 - 3 :: create table with PK -> create 5 index -> Load data (5 index)
        workload: goal2-3_create_5_indexes_then_load
        tableName: orders
        columns: 15
        rows: 300
        indexes: 5
        filePath: orders.csv
        stringLength: 32
        create_index_before_load: true
        create_index_after_load: false
