type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {{ username }}
password: {{ password }}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain: true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_G14_inventory;
            - CREATE TABLE THRPT_G14_inventory (id bigserial, warehouse_id int, category_id int, qty int, note text, PRIMARY KEY(id asc)) SPLIT AT VALUES ((133333), (266666));
            - CREATE INDEX idx_thrpt_g14_inventory_warehouse ON THRPT_G14_inventory (warehouse_id asc) SPLIT AT VALUES ((83333), (166666));
            - CREATE INDEX idx_thrpt_g14_inventory_category ON THRPT_G14_inventory (category_id asc) SPLIT AT VALUES ((1666), (3333));
        cleanup:
            - DROP TABLE IF EXISTS THRPT_G14_inventory;

        loadRules:
            - table: THRPT_G14_inventory
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: warehouse_id
                    util: CyclicSeqIntGen
                    params: [1, 25000]
                  - name: category_id
                    util: CyclicSeqIntGen
                    params: [1, 5000]
                  - name: qty
                    util: RandomNumber
                    params: [1, 10000]
                  - name: note
                    util: RandomAString
                    params: [100, 100]

        executeRules:
            - workload: THRPT_G14_bitmap_scan
              run:
                  - name: THRPT_G14_bitmap_scan
                    weight: 100
                    queries:
                        - query: SELECT * FROM THRPT_G14_inventory WHERE warehouse_id = ? OR category_id = ?;
                          bindings:
                              - util: RandomNumber
                                params: [1, 25000]
                              - util: RandomNumber
                                params: [1, 5000]