#TEST FOR YUGABYTE COLOCATED TABLES
type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://172.151.48.253:5433/yugabyte?sslmode=require
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: yugabyte
password: Password@321
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS pkey_range_lookup_v10_tbl_1;
            - DROP TABLE IF EXISTS pkey_range_lookup_v100_tbl_1;
            - DROP TABLE IF EXISTS pkey_range_lookup_v500_tbl_1;
            - DROP TABLE IF EXISTS indx_range_lookup_v10_tbl_1;
            - DROP TABLE IF EXISTS indx_range_lookup_v100_tbl_1;
            - DROP TABLE IF EXISTS indx_range_lookup_v500_tbl_1;
            - CREATE TABLE pkey_range_lookup_v10_tbl_1(col_varchar10_id_1 varchar(10), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_bigint_6 bigint,col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar100_1 varchar(100), col_varchar100_2 varchar(100), col_varchar500_1 varchar(500), PRIMARY KEY(col_varchar10_id_1 ASC));
            - CREATE TABLE pkey_range_lookup_v100_tbl_1(col_varchar100_id_1 varchar(100), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_bigint_6 bigint,col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_1 varchar(10), col_varchar100_1 varchar(100), col_varchar500_1 varchar(500), PRIMARY KEY(col_varchar100_id_1 ASC));
            - CREATE TABLE pkey_range_lookup_v500_tbl_1(col_varchar500_id_1 varchar(500), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_bigint_6 bigint,col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_1 varchar(10), col_varchar100_1 varchar(100), col_varchar100_2 varchar(100), PRIMARY KEY(col_varchar500_id_1 ASC));
            - CREATE TABLE indx_range_lookup_v10_tbl_1(col_varchar10_id_1 varchar(10), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_bigint_6 bigint,col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar100_1 varchar(100), col_varchar100_2 varchar(100), col_varchar500_1 varchar(500));
            - CREATE TABLE indx_range_lookup_v100_tbl_1(col_varchar100_id_1 varchar(100), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_bigint_6 bigint,col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_1 varchar(10), col_varchar100_1 varchar(100), col_varchar500_1 varchar(500));
            - CREATE TABLE indx_range_lookup_v500_tbl_1(col_varchar500_id_1 varchar(500), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_bigint_6 bigint,col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_1 varchar(10), col_varchar100_1 varchar(100), col_varchar100_2 varchar(100));
            - CREATE INDEX ON indx_range_lookup_v10_tbl_1(col_varchar10_id_1 ASC);
            - CREATE INDEX ON indx_range_lookup_v100_tbl_1(col_varchar100_id_1 ASC);
            - CREATE INDEX ON indx_range_lookup_v500_tbl_1(col_varchar500_id_1 ASC);
        loadRules:
            - table: pkey_range_lookup_v10_tbl_
              count: 1
              rows: 1000000
              columns:
                  - name: col_varchar10_id_
                    count: 1
                    util: PrimaryStringGen
                    params: [1, 10]
                  - name: col_bigint_
                    count: 6
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar100_
                    count: 2
                    util: RandomAString
                    params: [100, 100]
                  - name: col_varchar500_
                    count: 1
                    util: RandomAString
                    params: [500, 500]
            - table: pkey_range_lookup_v100_tbl_
              count: 1
              rows: 1000000
              columns:
                  - name: col_varchar100_id_
                    count: 1
                    util: PrimaryStringGen
                    params: [1, 100]
                  - name: col_bigint_
                    count: 6
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar10_
                    count: 1
                    util: RandomAString
                    params: [10, 10]
                  - name: col_varchar100_
                    count: 1
                    util: RandomAString
                    params: [100, 100]
                  - name: col_varchar500_
                    count: 1
                    util: RandomAString
                    params: [500, 500]
            - table: pkey_range_lookup_v500_tbl_
              count: 1
              rows: 1000000
              columns:
                  - name: col_varchar500_id_
                    count: 1
                    util: PrimaryStringGen
                    params: [1, 500]
                  - name: col_bigint_
                    count: 6
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar10_
                    count: 1
                    util: RandomAString
                    params: [10, 10]
                  - name: col_varchar100_
                    count: 2
                    util: RandomAString
                    params: [100, 100]

            - table: indx_range_lookup_v10_tbl_
              count: 1
              rows: 1000000
              columns:
                  - name: col_varchar10_id_
                    count: 1
                    util: PrimaryStringGen
                    params: [1, 10]
                  - name: col_bigint_
                    count: 6
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar100_
                    count: 2
                    util: RandomAString
                    params: [100, 100]
                  - name: col_varchar500_
                    count: 1
                    util: RandomAString
                    params: [500, 500]
            - table: indx_range_lookup_v100_tbl_
              count: 1
              rows: 1000000
              columns:
                  - name: col_varchar100_id_
                    count: 1
                    util: PrimaryStringGen
                    params: [1, 100]
                  - name: col_bigint_
                    count: 6
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar10_
                    count: 1
                    util: RandomAString
                    params: [10, 10]
                  - name: col_varchar100_
                    count: 1
                    util: RandomAString
                    params: [100, 100]
                  - name: col_varchar500_
                    count: 1
                    util: RandomAString
                    params: [500, 500]
            - table: indx_range_lookup_v500_tbl_
              count: 1
              rows: 1000000
              columns:
                  - name: col_varchar500_id_
                    count: 1
                    util: PrimaryStringGen
                    params: [1, 500]
                  - name: col_bigint_
                    count: 6
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar10_
                    count: 1
                    util: RandomAString
                    params: [10, 10]
                  - name: col_varchar100_
                    count: 2
                    util: RandomAString
                    params: [100, 100]

        executeRules:
            - workload: cattribVG2_ybc_pkey_v10_hash_point_lookup
              run:
                  - name: pkey_v10_hash_point_lookup_test
                    weight: 100
                    queries:
                        - query: select * from pkey_range_lookup_v10_tbl_1 where col_varchar10_id_1>'0'
            - workload: cattribVG2_ybc_pkey_v100_hash_point_lookup
              run:
                  - name: pkey_v100_hash_point_lookup_test
                    weight: 100
                    queries:
                        - query: select * from pkey_range_lookup_v100_tbl_1 where col_varchar100_id_1>'0'
            - workload: cattribVG2_ybc_pkey_v500_hash_point_lookup
              run:
                  - name: pkey_v500_hash_point_lookup_test
                    weight: 100
                    queries:
                        - query: select * from pkey_range_lookup_v500_tbl_1 where col_varchar500_id_1>'0'
            - workload: cattribVG2_ybc_indx_v10_hash_point_lookup
              run:
                  - name: indx_v10_hash_point_lookup_test
                    weight: 100
                    queries:
                        - query: select * from indx_range_lookup_v10_tbl_1 where col_varchar10_id_1>'0'
            - workload: cattribVG2_ybc_indx_v100_hash_point_lookup
              run:
                  - name: indx_v100_hash_point_lookup_test
                    weight: 100
                    queries:
                        - query: select * from indx_range_lookup_v100_tbl_1 where col_varchar100_id_1>'0'
            - workload: cattribVG2_ybc_indx_v500_hash_point_lookup
              run:
                  - name: indx_v500_hash_point_lookup_test
                    weight: 100
                    queries:
                        - query: select * from indx_range_lookup_v500_tbl_1 where col_varchar500_id_1>'0'