type: postgres
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_G13_employees;
            - ALTER DATABASE postgres SET enable_seqscan=off;
            - ALTER DATABASE postgres SET enable_bitmapscan=off;
            - CREATE TABLE THRPT_G13_employees (emp_id INT, name VARCHAR(10), email VARCHAR(20), salary INT, hire_date DATE, department VARCHAR(20), is_active BOOLEAN, last_login TIMESTAMP, PRIMARY KEY(emp_id));
            - CREATE INDEX idx_THRPT_G13_employees_dept_emp ON THRPT_G13_employees (department, emp_id);
        cleanup:
            - DROP TABLE IF EXISTS THRPT_G13_employees;
            - ALTER DATABASE postgres SET enable_seqscan TO DEFAULT;
            - ALTER DATABASE postgres SET enable_bitmapscan TO DEFAULT;

        loadRules:
            - table: THRPT_G13_employees
              rows: 1000000
              columns:
                  - name: emp_id
                    util: RandomUniqueIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [10, 10]
                  - name: email
                    util: RandomAString
                    params: [20, 20]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 100000, 2]
                  - name: hire_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: department
                    util: OneStringFromArray
                    params: [['Engineering', 'Sales', 'Marketing', 'Finance', 'IT', 'HR', 'Legal', 'Product']]
                  - name: is_active
                    util: RandomBoolean
                  - name: last_login
                    util: RandomTimestamp
                    params: [10000000]

        executeRules:
            - workload: THRPT_G13_row_locking
              run:
                  - name: THRPT_G13_row_locking
                    weight: 100
                    queries:
                        - query: SELECT * FROM THRPT_G13_employees WHERE department = ? and emp_id between ? and ? ORDER BY hire_date FOR UPDATE SKIP LOCKED;
                          bindings:
                              - util: OneStringFromArray
                                params: [['Engineering', 'Sales','Marketing','Finance','IT','HR','Legal','Product']]
                              - util: RandomNumber
                                params: [1, 990000]
                                referenceName: emp_id1
                              - util: ExpressionEval
                                params:
                                    - "emp_id1 + 10000"
