#TEST FOR POSTGRES TABLES
#GOAL10 Lookup on a table with 25 column with increasing count of filter columns
#Projection: All columns
#Filter: Increasing column count | Index keys
#Schema: 25 columns in a table with varchar datatype
#Purpose: Impact of increasing filter column count
#TESTS:
#Time to fetch all columns based on 2 non indexed column
#Time to fetch all columns based on 5 non indexed column
#Time to fetch all columns based on 10 non indexed column
type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
works:
    work:
        time_secs: 300
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS pkey_rangescan_fullTable_25column_2idx_1;
            - DROP TABLE IF EXISTS pkey_rangescan_fullTable_25column_5idx_1;
            - DROP TABLE IF EXISTS pkey_rangescan_fullTable_25column_10idx_1;
            - CREATE TABLE pkey_rangescan_fullTable_25column_2idx_1(col_varchar_id_1 varchar,col_varchar_id_2 varchar,col_varchar_id_3 varchar,col_varchar_id_4 varchar,col_varchar_id_5 varchar,col_varchar_id_6 varchar,col_varchar_id_7 varchar,col_varchar_id_8 varchar,col_varchar_id_9 varchar,col_varchar_id_10 varchar,col_varchar_id_11 varchar,col_varchar_1 varchar ,col_varchar_2 varchar ,col_varchar_3 varchar ,col_varchar_4 varchar ,col_varchar_5 varchar ,col_varchar_6 varchar ,col_varchar_7 varchar ,col_varchar_8 varchar ,col_varchar_9 varchar, col_varchar_10 varchar ,col_varchar_11 varchar ,col_varchar_12 varchar ,col_varchar_13 varchar ,col_varchar_14 varchar ,PRIMARY KEY(col_varchar_id_1));
            - CREATE TABLE pkey_rangescan_fullTable_25column_5idx_1(col_varchar_id_1 varchar,col_varchar_id_2 varchar,col_varchar_id_3 varchar,col_varchar_id_4 varchar,col_varchar_id_5 varchar,col_varchar_id_6 varchar,col_varchar_id_7 varchar,col_varchar_id_8 varchar,col_varchar_id_9 varchar,col_varchar_id_10 varchar,col_varchar_id_11 varchar,col_varchar_1 varchar ,col_varchar_2 varchar ,col_varchar_3 varchar ,col_varchar_4 varchar ,col_varchar_5 varchar ,col_varchar_6 varchar ,col_varchar_7 varchar ,col_varchar_8 varchar ,col_varchar_9 varchar, col_varchar_10 varchar ,col_varchar_11 varchar ,col_varchar_12 varchar ,col_varchar_13 varchar ,col_varchar_14 varchar ,PRIMARY KEY(col_varchar_id_1));
            - CREATE TABLE pkey_rangescan_fullTable_25column_10idx_1(col_varchar_id_1 varchar,col_varchar_id_2 varchar,col_varchar_id_3 varchar,col_varchar_id_4 varchar,col_varchar_id_5 varchar,col_varchar_id_6 varchar,col_varchar_id_7 varchar,col_varchar_id_8 varchar,col_varchar_id_9 varchar,col_varchar_id_10 varchar,col_varchar_id_11 varchar,col_varchar_1 varchar ,col_varchar_2 varchar ,col_varchar_3 varchar ,col_varchar_4 varchar ,col_varchar_5 varchar ,col_varchar_6 varchar ,col_varchar_7 varchar ,col_varchar_8 varchar ,col_varchar_9 varchar, col_varchar_10 varchar ,col_varchar_11 varchar ,col_varchar_12 varchar ,col_varchar_13 varchar ,col_varchar_14 varchar ,PRIMARY KEY(col_varchar_id_1));
            - CREATE INDEX ON pkey_rangescan_fullTable_25column_2idx_1(col_bigint_id_2,col_bigint_id_3);
            - CREATE INDEX ON pkey_rangescan_fullTable_25column_5idx_1(col_bigint_id_2,col_bigint_id_3,col_bigint_id_4,col_bigint_id_5,col_bigint_id_6);
            - CREATE INDEX ON pkey_rangescan_fullTable_25column_10idx_1(col_bigint_id_2,col_bigint_id_3,col_bigint_id_4,col_bigint_id_5,col_bigint_id_6,col_bigint_id_7,col_bigint_id_8,col_bigint_id_9,col_bigint_id_10,col_bigint_id_11);

        loadRules:
            -   table: pkey_rangescan_fullTable_25column_2idx_
                count: 1
                rows: 1000000
                columns:
                    -   name: col_varchar_id_
                        count: 11
                        util: PrimaryStringGen
                        params: [ 1, 128 ]
                    -   name: col_varchar_
                        count: 14
                        util: RandomAString
                        params: [ 16, 16 ]
            -   table: pkey_rangescan_fullTable_25column_5idx_
                count: 1
                rows: 1000000
                columns:
                    -   name: col_varchar_id_
                        count: 11
                        util: PrimaryStringGen
                        params: [ 1, 128 ]
                    -   name: col_varchar_
                        count: 14
                        util: RandomAString
                        params: [ 16, 16 ]
            -   table: pkey_rangescan_fullTable_25column_10idx_
                count: 1
                rows: 1000000
                columns:
                    -   name: col_varchar_id_
                        count: 11
                        util: PrimaryStringGen
                        params: [ 1, 128 ]
                    -   name: col_varchar_
                        count: 14
                        util: RandomAString
                        params: [ 16, 16 ]
        executeRules:
            - workload: cattribG10_pg_idxRange_table25column_2idxCol_noRowsFetched
              run:
                  - name: idxRange_table25column_2idxCol_noRowsFetched
                    weight: 100
                    queries:
                        - query: select * from pkey_rangescan_fullTable_25column_2idx_1 where col_varchar_id_2='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_3='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab'
            -   workload: cattribG10_pg_idxRange_table25column_2idxCol_1RowFetched
                run:
                    -   name: idxRange_table25column_2idxCol_1RowFetched
                        weight: 100
                        queries:
                            -   query: select * from pkey_rangescan_fullTable_25column_2idx_1 where col_varchar_id_2='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_3='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
            - workload: cattribG10_pg_idxRange_table25column_5idxCol_noRowsFetched
              run:
                  - name: idxRange_table25column_5idxCol_noRowsFetched
                    weight: 100
                    queries:
                        - query: select * from pkey_rangescan_fullTable_25column_5idx_1 where col_varchar_id_2='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_3='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_4='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_5='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_6='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab'
            -   workload: cattribG10_pg_idxRange_table25column_5idxCol_1RowFetched
                run:
                    -   name: idxRange_table25column_5idxCol_1RowFetched
                        weight: 100
                        queries:
                            -   query: select * from pkey_rangescan_fullTable_25column_5idx_1 where col_varchar_id_2='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_3='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_4='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_5='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_6='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
            - workload: cattribG10_pg_idxRange_table25column_10idxCol_noRowsFetched
              run:
                  - name: idxRange_table25column_10idxCol_noRowsFetched
                    weight: 100
                    queries:
                        - query: select * from pkey_rangescan_fullTable_25column_10idx_1 where col_varchar_id_2='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_3='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_4='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_5='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_6='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_7='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_8='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_9='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_10='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab' and col_varchar_id_11='1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab'
            -   workload: cattribG10_pg_idxRange_table25column_10idxCol_1RowFetched
                run:
                    -   name: idxRange_table25column_10idxCol_1RowFetched
                        weight: 100
                        queries:
                            -   query: select * from pkey_rangescan_fullTable_25column_10idx_1 where col_varchar_id_2='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_3='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_4='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_5='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_6='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_7='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_8='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_9='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_10='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and col_varchar_id_11='999998aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

