type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
disable_explain: true
works:
    work:
        time_secs: 1800
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table IF EXISTS nets_10M_1;

        cleanup:
            - drop table IF EXISTS nets_10M_1;

        loadRules:

            - table: nets_1TB_
              count: 1
              rows: 693607040
              columns:
                    - name: op_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [ 970392960, 50 ]
                    - name: work_type_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: work_id_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: sequence_id_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: source_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: owner_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: state_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: resource_id_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: tracing_data_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: created_
                      count: 1
                      util: CurrentTime
                    - name: modified_
                      count: 1
                      util: CurrentTime
                    - name: timeout_
                      count: 1
                      util: CurrentTime
                    - name: retry_count_
                      count: 1
                      util: RandomInt
                      params: [ 1, 50 ]
                    - name: db_user_id_
                      count: 1
                      util: HashedRandomString
                      params: [ 1, 500, 10]
                    - name: shard_id_
                      count: 1
                      util: RandomNumber
                      params: [ 1, 50 ]
                    - name: ingest_time_
                      count: 1
                      util: CurrentTime
                    - name: label_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]
                    - name: metadata_
                      count: 1
                      util: RandomAString
                      params: [ 50, 50 ]


        executeRules:


            - workload: MG1_5_Analyze_1TB
              time_secs: 1800
              run:
                  - name: analyze_1
                    weight: 100
                    queries:
                        - query: analyze nets_1TB_1
