type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 4
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - drop table if exists table_10_cols;
            - drop table if exists table_100_cols;
            - drop table if exists table_1000_cols;
            - CREATE TABLE table_10_cols (id INT, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, col5 TEXT, col6 TEXT, col7 TEXT, col8 TEXT, col9 TEXT, col10 TEXT,primary key (id asc));
            - CREATE TABLE table_100_cols (id INT , col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, col5 TEXT, col6 TEXT, col7 TEXT, col8 TEXT, col9 TEXT, col10 TEXT, col11 TEXT, col12 TEXT, col13 TEXT, col14 TEXT, col15 TEXT, col16 TEXT, col17 TEXT, col18 TEXT, col19 TEXT, col20 TEXT, col21 TEXT, col22 TEXT, col23 TEXT, col24 TEXT, col25 TEXT, col26 TEXT, col27 TEXT, col28 TEXT, col29 TEXT, col30 TEXT, col31 TEXT, col32 TEXT, col33 TEXT, col34 TEXT, col35 TEXT, col36 TEXT, col37 TEXT, col38 TEXT, col39 TEXT, col40 TEXT, col41 TEXT, col42 TEXT, col43 TEXT, col44 TEXT, col45 TEXT, col46 TEXT, col47 TEXT, col48 TEXT, col49 TEXT, col50 TEXT, col51 TEXT, col52 TEXT, col53 TEXT, col54 TEXT, col55 TEXT, col56 TEXT, col57 TEXT, col58 TEXT, col59 TEXT, col60 TEXT, col61 TEXT, col62 TEXT, col63 TEXT, col64 TEXT, col65 TEXT, col66 TEXT, col67 TEXT, col68 TEXT, col69 TEXT, col70 TEXT, col71 TEXT, col72 TEXT, col73 TEXT, col74 TEXT, col75 TEXT, col76 TEXT, col77 TEXT, col78 TEXT, col79 TEXT, col80 TEXT, col81 TEXT, col82 TEXT, col83 TEXT, col84 TEXT, col85 TEXT, col86 TEXT, col87 TEXT, col88 TEXT, col89 TEXT, col90 TEXT, col91 TEXT, col92 TEXT, col93 TEXT, col94 TEXT, col95 TEXT, col96 TEXT, col97 TEXT, col98 TEXT, col99 TEXT, col100 TEXT,primary key (id asc));
        cleanup:
            - drop table if exists table_10_cols;
            - drop table if exists table_100_cols;
        loadRules:
            -   table: table_10_cols
                rows: 100000
                columns:
                    -   name: id
                        util: PrimaryIntGen
                        params: [ 1, 100000 ]
                    -   name: col
                        count: 10
                        util: RandomAString
                        params: [ 5, 5 ]
            -   table: table_100_cols
                rows: 100000
                columns:
                    -   name: id
                        util: PrimaryIntGen
                        params: [ 1, 100000 ]
                    -   name: col
                        count: 100
                        util: RandomAString
                        params: [ 5, 5 ]
        executeRules:
            -   workload: 10_col_test
                run:
                    -   name: Insert_with_10cols_test
                        weight: 100
                        queries:
                            -   query: INSERT INTO table_10_cols values (?,?,?,?,?,?,?,?,?,?,?)
                                count: 10
                                bindings:
                                    -   util: PrimaryIntGen
                                        params: [ 1000001, 9000000 ]
                                    -   util: RandomAString
                                        count: 10
                                        params: [ 5, 5 ]
            -   workload: 100_col_test
                run:
                    -   name: Insert_with_100_cols_test
                        weight: 100
                        queries:
                            -   query: INSERT INTO table_100_cols values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                                count: 10
                                bindings:
                                    -   util: PrimaryIntGen
                                        params: [ 1000001, 9000000 ]
                                    -   util: RandomAString
                                        count: 100
                                        params: [ 5, 5 ]
