type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true&connectTimeout=144000&socketTimeout=14400&tcpKeepAlive=true
username: {{username}}
password: {{password}}
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: true
loaderthreads: 1
terminals: 1
works:
    work:
        time_secs: 10
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal2
    properties:
        # Goal2 - 1 :: create table with PK -> create 1 index -> Load data (1 index)
        tableName: orders
        columns: 15
        rows: 3000000
        indexes: 1
        filePath: orders.csv
        stringLength: 32
        create_index_before_load: true
        create_index_after_load: false

#        # Goal2 - 2 :: create table with PK -> load data -> create 1 index
#        tableName: orders
#        columns: 15
#        rows: 3000000
#        indexes: 1
#        filePath: orders.csv
#        stringLength: 32
#        create_index_before_load: false
#        create_index_after_load: true
#
#        # Goal2 - 3 :: create table with PK -> create 5 index -> Load data (5 index)
#        tableName: orders
#        columns: 15
#        rows: 3000000
#        indexes: 5
#        filePath: orders.csv
#        stringLength: 32
#        create_index_before_load: true
#        create_index_after_load: false
#
#        # Goal2 - 2 :: create table with PK -> load data -> create 1 index
#        tableName: orders
#        columns: 15
#        rows: 3000000
#        indexes: 5
#        filePath: orders.csv
#        stringLength: 32
#        create_index_before_load: false
#        create_index_after_load: true

