type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS projects_with_part;
            - DROP TABLE IF EXISTS projects_without_part;

            - DROP TABLE IF EXISTS projects_rem_0;
            - DROP TABLE IF EXISTS projects_rem_1;
            - DROP TABLE IF EXISTS projects_rem_2;
            - DROP TABLE IF EXISTS projects_rem_3;
            - DROP TABLE IF EXISTS projects_rem_4;

            - create table projects_with_part (id int, name varchar(20) NOT NULL, uid int, version int, created_at date,PRIMARY KEY (id, uid)) PARTITION BY HASH (uid);
            - CREATE TABLE projects_rem_0 PARTITION OF projects_with_part FOR VALUES WITH (MODULUS 5, REMAINDER 0);
            - CREATE TABLE projects_rem_1 PARTITION OF projects_with_part FOR VALUES WITH (MODULUS 5, REMAINDER 1);
            - CREATE TABLE projects_rem_2 PARTITION OF projects_with_part FOR VALUES WITH (MODULUS 5, REMAINDER 2);
            - CREATE TABLE projects_rem_3 PARTITION OF projects_with_part FOR VALUES WITH (MODULUS 5, REMAINDER 3);
            - CREATE TABLE projects_rem_4 PARTITION OF projects_with_part FOR VALUES WITH (MODULUS 5, REMAINDER 4);

            - create table projects_without_part (id int, name varchar(20) NOT NULL, uid int, version int, created_at date,PRIMARY KEY (id, uid));
        cleanup:
            - DROP TABLE IF EXISTS projects_with_part;
            - DROP TABLE IF EXISTS projects_without_part;

            - DROP TABLE IF EXISTS projects_rem_0;
            - DROP TABLE IF EXISTS projects_rem_1;
            - DROP TABLE IF EXISTS projects_rem_2;
            - DROP TABLE IF EXISTS projects_rem_3;
            - DROP TABLE IF EXISTS projects_rem_4;
        loadRules:
            - table: projects_with_part
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: version
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: created_at
                    util: CyclicSeqDateGen
                    params: [2001,2025]

            - table: projects_without_part
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: version
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: created_at
                    util: CyclicSeqDateGen
                    params: [2001,2025]

        # afterLoad:
        #     - ALTER TABLE employees_with_fk add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects(id);
            
        executeRules:
            - workload: select_with_part
              run:
                  - name: select_with_part
                    weight: 100
                    queries:
                        - query: SELECT * FROM projects_with_part where uid=? or uid=?;
                          bindings:
                              - count: 2
                                util: RandomInt
                                params: [1, 100000]

            - workload: select_without_part
              run:
                  - name: select_without_part
                    weight: 100
                    queries:
                        - query: SELECT * FROM projects_without_part where uid=? or uid=?;
                          bindings:
                              - count: 2
                                util: RandomInt
                                params: [1, 100000]
                              
            - workload: insert_with_part
              run:
                  - name: insert_with_part
                    weight: 100
                    queries:
                        - query: insert into projects_with_part values(?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [100001, 500000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: PrimaryIntGen
                                params: [1, 100000]
                              - util: PrimaryIntGen
                                params: [1, 100000]
                              - util: CyclicSeqDateGen
                                params: [2001,2025]
            
            - workload: insert_without_part
              run:
                  - name: insert_without_part
                    weight: 100
                    queries:
                        - query: insert into projects_without_part values(?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [100001, 500000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: PrimaryIntGen
                                params: [1, 100000]
                              - util: PrimaryIntGen
                                params: [1, 100000]
                              - util: CyclicSeqDateGen
                                params: [2001,2025]

            - workload: update_with_part
              run:
                  - name: update_with_part
                    weight: 100
                    queries:
                        - query: update projects_with_part set version=version+1 where uid=? or uid=?;
                          bindings:
                            - count: 2
                              util: RandomInt
                              params: [1, 100000]

            - workload: update_without_part
              run:
                  - name: update_without_part
                    weight: 100
                    queries:
                        - query: update projects_without_part set version=version+1 where uid=? or uid=?;
                          bindings:
                            - count: 2
                              util: RandomInt
                              params: [1, 100000]

            - workload: delete_with_part
              run:
                  - name: delete_with_part
                    weight: 100
                    queries:
                        - query: delete from projects_with_part where uid=? or uid=?;
                          bindings:
                            - count: 2
                              util: PrimaryIntGen
                              params: [1, 100000]

            - workload: delete_without_part
              run:
                  - name: delete_without_part
                    weight: 100
                    queries:
                        - query: delete from projects_without_part where uid=? or uid=?;
                          bindings:
                            - count: 2
                              util: PrimaryIntGen
                              params: [1, 100000]