type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS employees_with_part;
            - DROP TABLE IF EXISTS employees_without_part;
            - DROP TABLE IF EXISTS employees_without_fk;
            - DROP TABLE IF EXISTS projects_with_part;
            - DROP TABLE IF EXISTS projects_without_part;

            - DROP TABLE IF EXISTS projects_sales;
            - DROP TABLE IF EXISTS projects_eng;
            - DROP TABLE IF EXISTS projects_hr;
            - DROP TABLE IF EXISTS projects_default;

            - create table projects_with_part (id int, name varchar(20) NOT NULL, dept varchar(15), created_at date,PRIMARY KEY (id, dept)) PARTITION BY LIST (dept);
            - CREATE TABLE projects_sales PARTITION OF projects_with_part FOR VALUES IN ('Sales');
            - CREATE TABLE projects_eng PARTITION OF projects_with_part FOR VALUES IN ('Engineering');
            - CREATE TABLE projects_hr PARTITION OF projects_with_part FOR VALUES IN ('HR');
            - CREATE TABLE projects_default PARTITION OF projects_with_part DEFAULT;

            - create table projects_without_part (id int, name varchar(20) NOT NULL, dept varchar(15), created_at date,PRIMARY KEY (id, dept));

            - create table employees_with_part (id int primary key, name varchar(50) not null, project_id int, project_dept varchar(15), hired_at date);
            - create table employees_without_part (id int primary key, name varchar(50) not null, project_id int, project_dept varchar(15), hired_at date);
            - create table employees_without_fk (id int primary key, name varchar(50) not null, project_id int, project_dept varchar(15), hired_at date);
        cleanup:
            - DROP TABLE IF EXISTS employees_with_part;
            - DROP TABLE IF EXISTS employees_without_part;
            - DROP TABLE IF EXISTS employees_without_fk;
            - DROP TABLE IF EXISTS projects_with_part;
            - DROP TABLE IF EXISTS projects_without_part;

            - DROP TABLE IF EXISTS projects_sales;
            - DROP TABLE IF EXISTS projects_eng;
            - DROP TABLE IF EXISTS projects_hr;
            - DROP TABLE IF EXISTS projects_default;
        loadRules:
            - table: projects_with_part
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: dept
                    util: SeqStringGenFromArray
                    params: [['Sales','Engineering','HR','Anonymous']]
                  - name: created_at
                    util: RandomDateBtwYears
                    params: [2000,2025]

            - table: projects_without_part
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: dept
                    util: SeqStringGenFromArray
                    params: [['Sales','Engineering','HR','Anonymous']]
                  - name: created_at
                    util: RandomDateBtwYears
                    params: [2000,2025]

            - table: employees_with_part
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]
                  - name: project_dept
                    util: SeqStringGenFromArray
                    params: [['Sales','Engineering','HR','Anonymous']]
                  - name: hired_at
                    util: RandomDateBtwYears
                    params: [2000,2025]

            - table: employees_without_part
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]
                  - name: project_dept
                    util: SeqStringGenFromArray
                    params: [['Sales','Engineering','HR','Anonymous']]
                  - name: hired_at
                    util: RandomDateBtwYears
                    params: [2000,2025]

            - table: employees_without_fk
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]
                  - name: project_dept
                    util: SeqStringGenFromArray
                    params: [['Sales','Engineering','HR','Anonymous']]
                  - name: hired_at
                    util: RandomDateBtwYears
                    params: [2000,2025]

        afterLoad:
            - ALTER TABLE employees_with_part add CONSTRAINT fk_project foreign key (project_id, project_dept) references projects_with_part(id, dept) on delete cascade on update cascade;
            - ALTER TABLE employees_without_part add CONSTRAINT fk_project foreign key (project_id, project_dept) references projects_without_part(id, dept) on delete cascade on update cascade;
            
        executeRules:
                              
            - workload: insert_with_part
              run:
                  - name: insert_with_part
                    weight: 100
                    queries:
                        - query: insert into employees_with_part values(?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [1000001, 5000000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: CyclicSeqIntGen
                                params: [1,100000]
                              - util: SeqStringGenFromArray
                                params: [['Sales','Engineering','HR','Anonymous']]
                              - util: RandomDateBtwYears
                                params: [2000,2025]
            
            - workload: insert_without_part
              run:
                  - name: insert_without_part
                    weight: 100
                    queries:
                        - query: insert into employees_without_part values(?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [1000001, 5000000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: CyclicSeqIntGen
                                params: [1,100000]
                              - util: SeqStringGenFromArray
                                params: [['Sales','Engineering','HR','Anonymous']]
                              - util: RandomDateBtwYears
                                params: [2000,2025]

            - workload: insert_without_fk
              run:
                  - name: insert_without_fk
                    weight: 100
                    queries:
                        - query: insert into employees_without_fk values(?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [1000001, 5000000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: CyclicSeqIntGen
                                params: [1,100000]
                              - util: SeqStringGenFromArray
                                params: [['Sales','Engineering','HR','Anonymous']]
                              - util: RandomDateBtwYears
                                params: [2000,2025]

            - workload: update_with_part
              run:
                  - name: update_with_part
                    weight: 100
                    queries:
                        - query: update employees_with_part set project_id=?, project_dept=? where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]
                            - util: SeqStringGenFromArray
                              params: [['Sales','Engineering','HR','Anonymous']]
                            - util: RandomInt
                              params: [1, 1000000]

            - workload: update_without_part
              run:
                  - name: update_without_part
                    weight: 100
                    queries:
                        - query: update employees_without_part set project_id=?, project_dept=? where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]
                            - util: SeqStringGenFromArray
                              params: [['Sales','Engineering','HR','Anonymous']]
                            - util: RandomInt
                              params: [1, 1000000]

            - workload: update_without_fk
              run:
                  - name: update_without_fk
                    weight: 100
                    queries:
                        - query: update employees_without_fk set project_id=?, project_dept=? where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]
                            - util: SeqStringGenFromArray
                              params: [['Sales','Engineering','HR','Anonymous']]
                            - util: RandomInt
                              params: [1, 1000000]