type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 3
collect_pg_stat_statements: true
use_dist_in_explain : true
analyze_on_all_tables: true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 3
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS test_table_hash;
            - CREATE TABLE test_data_hash (id SERIAL PRIMARY KEY, data TEXT);
        cleanup:
            - DROP TABLE IF EXISTS test_table_hash;
        loadRules:
            - table: test_table_hash
              rows: 10000
              columns:
                  - name: data
                    util: OneStringFromArray
                    params: ['100000']

        executeRules:
            - workload: advisory_locks_select
              run:
                  - name: advisory_locks_select
                    weight: 100
                    queries:
                        - query: "SELECT pg_advisory_lock(?);"
                          bindings:
                              - util: OneStringFromArray
                                params: ['100000']
                        - query: "SELECT * FROM test_data WHERE id = ?"
                          bindings:
                              - util: OneStringFromArray
                                params: [ '100000' ]
                        - query: "SELECT pg_advisory_unlock(?);"
                          bindings:
                              -  util: OneStringFromArray
                                 params: [ '100000' ]



