type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://172.156.42.143:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password: Stiwary@benchmarking16
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
works:
    work:
        time: 5
        active_terminals: 1
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBMicroBenchmarkInsertsSequential
    properties:
        setAutoCommit : true
        create :
            - DROP PROCEDURE if exists insert_demo;
            - CREATE PROCEDURE insert_demo(_numRows int)
                LANGUAGE plpgsql
                AS $$
                DECLARE
                BEGIN
                insert into demo (id, col1, col2, col3, col4, col5, col6, col7, col8, col9, col10) select n, n, n, n, n, n, n, n, n, n, n from generate_series(1,_numRows) n;
                END;
                $$;
            - drop table if exists demo;
            - create table demo (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int) split into 1 tablets;
            - create unique index demo_idx1 on demo(col1) split into 1 tablets;
            - create unique index demo_idx2 on demo(col2) split into 1 tablets;
            - create unique index demo_idx3 on demo(col3) split into 1 tablets;
            - create unique index demo_idx4 on demo(col4) split into 1 tablets;
            - create unique index demo_idx5 on demo(col5) split into 1 tablets;
            - create unique index demo_idx6 on demo(col6) split into 1 tablets;
            - create unique index demo_idx7 on demo(col7) split into 1 tablets;
            - create unique index demo_idx8 on demo(col8) split into 1 tablets;
            - create unique index demo_idx9 on demo(col9) split into 1 tablets;
            - create unique index demo_idx10 on demo(col10) split into 1 tablets;
