#!/usr/bin/env python3
"""Make the agent-neutral skills in skills/ available to Claude Code.

Same pattern as perf-devops/skills/install.py: skills/<name>/ is the single source of truth, and
.claude/skills/ only holds thin generated wrappers that point back to it. Other agents (Cursor,
Codex, ...) read skills/ directly via AGENTS.md.

    python3 skills/install.py claude-project        # .claude/skills/<name>/SKILL.md wrappers (commit them)
    python3 skills/install.py claude-user           # ~/.claude/skills/<name>/SKILL.md wrappers (just for you)
    python3 skills/install.py claude-user --remove  # remove only the wrappers this script created
    python3 skills/install.py zip [--out DIR]       # self-contained zips for claude.ai / Claude Desktop upload
    python3 skills/install.py check                 # exit 1 if project wrappers are stale

Wrappers copy the canonical frontmatter (so the skill triggers on the same description) and tell
the agent to read the canonical SKILL.md. Directory symlinks are not used because Claude Code does
not reliably discover skills through them.
"""

import argparse
import re
import shutil
import sys
import zipfile
from pathlib import Path

SKILLS = Path(__file__).resolve().parent
REPO = SKILLS.parent
MARKER = "generated by skills/install.py"
NAME_RE = re.compile(r"^[a-z0-9-]{1,64}$")
PROJECT_TARGETS = {"claude": REPO / ".claude" / "skills"}


def skills():
    out = []
    for d in sorted(p for p in SKILLS.iterdir() if p.is_dir() and not p.name.startswith(("_", ".")) and p.name != "dist"):
        f = d / "SKILL.md"
        if not f.exists():
            continue
        text = f.read_text()
        m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        if not m:
            sys.exit(f"{f}: missing YAML frontmatter")
        fm = m.group(1)
        name = re.search(r"^name:\s*(.+)$", fm, re.M).group(1).strip()
        desc = re.search(r"^description:\s*(.+)$", fm, re.M).group(1).strip()
        problems = []
        if name != d.name or not NAME_RE.match(name):
            problems.append(f"name '{name}' must equal the folder name and match {NAME_RE.pattern}")
        if len(desc) > 1024:
            problems.append(f"description is {len(desc)} chars (max 1024)")
        if re.search(r"[<>]", desc):
            problems.append("description must not contain angle brackets")
        if problems:
            sys.exit(f"{f}: " + "; ".join(problems))
        out.append((name, fm, d))
    return out


def wrapper(name, fm, target_path):
    return (f"---\n{fm}\n---\n\n"
            f"<!-- {MARKER}; edit skills/{name}/SKILL.md instead, then re-run the installer -->\n\n"
            f"# {name}\n\n"
            f"The instructions for this skill live in **`{target_path}`**. Read that file now and follow it.\n"
            f"Scripts and data it mentions are relative to that file's folder "
            f"(`{Path(target_path).parent}/`); run scripts from the benchbase repo root.\n")


def _project(targets, check):
    wanted = {name: wrapper(name, fm, f"skills/{name}/SKILL.md") for name, fm, _ in skills()}
    rc = 0
    for tool in targets:
        dest_root = PROJECT_TARGETS[tool]
        rel = dest_root.relative_to(REPO)
        orphans = [p.name for p in dest_root.iterdir() if p.is_dir() and p.name not in wanted
                   and (p / "SKILL.md").exists() and MARKER in (p / "SKILL.md").read_text()] \
            if dest_root.exists() else []
        if check:
            stale = [n for n, body in wanted.items()
                     if not (dest_root / n / "SKILL.md").exists() or (dest_root / n / "SKILL.md").read_text() != body]
            if stale or orphans:
                print(f"{rel}: stale {stale}  orphaned {orphans}  -> run: python3 skills/install.py claude-project")
                rc = 1
            else:
                print(f"{rel}: wrappers are up to date")
            continue
        for name, body in wanted.items():
            f = dest_root / name / "SKILL.md"
            if f.exists() and MARKER not in f.read_text():
                print(f"skip {rel}/{name}: exists and was not created by this installer")
                continue
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(body)
            print(f"wrote {rel}/{name}/SKILL.md")
        for n in orphans:
            shutil.rmtree(dest_root / n)
            print(f"removed stale wrapper {rel}/{n}")
    return rc


def cmd_claude_project(args):
    return _project(["claude"], False)


def cmd_check(args):
    return _project(["claude"], True)


def cmd_claude_user(args):
    dest_root = Path.home() / ".claude" / "skills"
    ours = {n for n, _, _ in skills()}
    if args.remove:
        for n in sorted(ours):
            f = dest_root / n / "SKILL.md"
            if f.exists() and MARKER in f.read_text():
                shutil.rmtree(dest_root / n)
                print(f"removed ~/.claude/skills/{n}")
        return 0
    for name, fm, d in skills():
        target = dest_root / name / "SKILL.md"
        if target.exists() and MARKER not in target.read_text():
            print(f"skip ~/.claude/skills/{name}: exists and was not created by this installer")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(wrapper(name, fm, str(d / "SKILL.md")))
        print(f"wrote ~/.claude/skills/{name}/SKILL.md -> {d / 'SKILL.md'}")
    return 0


def cmd_zip(args):
    out_dir = Path(args.out) if args.out else SKILLS / "dist"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, _, d in skills():
        zpath = out_dir / f"{name}.zip"
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
            for f in d.rglob("*"):
                rel = f.relative_to(d)
                if f.is_file() and "__pycache__" not in f.parts and rel.parts[0] != "evals" \
                        and not any(part.startswith(".") for part in rel.parts):
                    z.write(f, f"{name}/{rel}")
        print(f"wrote {zpath} ({zpath.stat().st_size // 1024} KB)")
    return 0


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("claude-project").set_defaults(fn=cmd_claude_project)
    sub.add_parser("check").set_defaults(fn=cmd_check)
    s = sub.add_parser("claude-user")
    s.add_argument("--remove", action="store_true")
    s.set_defaults(fn=cmd_claude_user)
    s = sub.add_parser("zip")
    s.add_argument("--out")
    s.set_defaults(fn=cmd_zip)
    args = p.parse_args()
    sys.exit(args.fn(args) or 0)


if __name__ == "__main__":
    main()
