type: postgres
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 1
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 4
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_between_1mb_row;
            - CREATE TABLE THRPT_between_1mb_row (id INT, lookup_key INT, payload TEXT, PRIMARY KEY(id));

        cleanup:
            - DROP TABLE IF EXISTS THRPT_between_1mb_row;

        loadRules:
            - table: THRPT_between_1mb_row
              rows: 10000
              columns:
                  - name: id
                    util: RandomUniqueIntGen
                    params: [1, 10000]
                  - name: lookup_key
                    util: RandomUniqueIntGen
                    params: [1, 10000]
                  - name: payload
                    util: RandomAString
                    params: [1048576, 1048576]
        executeRules:
            - workload: THRPT_between_1mb_row
              run:
                  - name: THRPT_between_1mb_row
                    weight: 100
                    queries:
                        - query: SELECT * FROM THRPT_between_1mb_row WHERE id between ? and ?;
                          bindings:
                              - util: RandomNumber
                                params: [1, 9900]
                                referenceName: id1
                              - util: ExpressionEval
                                params:
                                    - "id1 + 100"
