type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS employees_with_fk_on_pk;
            - DROP TABLE IF EXISTS employees_with_fk_on_uniqueCol;
            - DROP TABLE IF EXISTS employees_without_fk;
            - DROP TABLE IF EXISTS projects_with_pk;
            - DROP TABLE IF EXISTS projects_with_uniqueCol;
            - create table projects_with_pk(id int primary key, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table projects_with_uniqueCol(id int primary key, uid int unique, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table employees_with_fk_on_pk(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(8,2), project_id int not null);
            - create table employees_with_fk_on_uniqueCol(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(8,2), project_id int not null);
            - create table employees_without_fk(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(8,2), project_id int not null);
        cleanup:
            - DROP TABLE IF EXISTS employees_with_fk_on_pk;
            - DROP TABLE IF EXISTS employees_with_fk_on_uniqueCol;
            - DROP TABLE IF EXISTS employees_without_fk;
            - DROP TABLE IF EXISTS projects_with_pk;
            - DROP TABLE IF EXISTS projects_with_uniqueCol;
        loadRules:
            - table: projects_with_pk
              rows: 10000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: projects_with_uniqueCol
              rows: 10000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: employees_without_fk
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomInt
                    params: [1,10000]
              
            - table: employees_with_fk_on_pk
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomInt
                    params: [1,10000]

            - table: employees_with_fk_on_uniqueCol
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomInt
                    params: [1,10000]

        afterLoad:
            - ALTER TABLE employees_with_fk_on_pk add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_pk(id);
            - ALTER TABLE employees_with_fk_on_uniqueCol add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_uniqueCol(uid);
            
        executeRules:

            - workload: FK_G1_fk-on-pk_insert
              run:
                  - name: FK_G1_fk-on-pk_insert
                    weight: 100
                    queries:
                        - query: insert into employees_with_fk_on_pk values(?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [100001, 900000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 100]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomNumber
                                params: [1,10000]

            - workload: FK_G1_fk-on-pk_update
              run:
                  - name: FK_G1_fk-on-pk_update
                    weight: 100
                    queries:
                        - query: update employees_with_fk_on_pk set project_id=? where id=?;
                          bindings:
                            - util: RandomInt
                              params: [1, 10000]
                            - util: RandomInt
                              params: [1, 100000]

            - workload: FK_G1_fk-on-uniqueCol_insert
              run:
                  - name: FK_G1_fk-on-uniqueCol_insert
                    weight: 100
                    queries:
                        - query: insert into employees_with_fk_on_uniqueCol values(?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [100001, 900000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 100]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomNumber
                                params: [1,10000]

            - workload: FK_G1_fk-on-uniqueCol_update
              run:
                  - name: FK_G1_fk-on-uniqueCol_update
                    weight: 100
                    queries:
                        - query: update employees_with_fk_on_uniqueCol set project_id=? where id=?;
                          bindings:
                            - util: RandomInt
                              params: [1, 10000]
                            - util: RandomInt
                              params: [1, 100000]

            - workload: FK_G1_no-fk_insert
              run:
                  - name: FK_G1_no-fk_insert
                    weight: 100
                    queries:
                        - query: insert into employees_without_fk values(?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [100001, 900000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 100]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomInt
                                params: [1,10000]
                                
            - workload: FK_G1_no-fk_update
              run:
                  - name: FK_G1_no-fk_update
                    weight: 100
                    queries:
                        - query: update employees_without_fk set project_id=? where id=?;
                          bindings:
                            - util: RandomInt
                              params: [1, 10000]
                            - util: RandomInt
                              params: [1, 100000]