type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS employees_with_indx;
            - DROP TABLE IF EXISTS projects_with_indx;
            - DROP TABLE IF EXISTS dept_with_indx;
            - DROP TABLE IF EXISTS employees_without_indx;
            - DROP TABLE IF EXISTS projects_without_indx;
            - DROP TABLE IF EXISTS dept_without_indx;

            - create table dept_without_indx(id int primary key, uid int unique, name varchar(20) not null);
            - create table dept_with_indx(id int primary key, uid int unique, name varchar(20) not null);
            - create table projects_with_indx(id int primary key, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2), dept_id int not null);
            - create table employees_with_indx(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(8,2), dept_id int not null);
            - create table projects_without_indx(id int primary key, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2), dept_id int not null);
            - create table employees_without_indx(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(8,2), dept_id int not null);
            - create index dept_index on dept_with_indx(uid);
        cleanup:
            - DROP TABLE IF EXISTS employees_with_indx;
            - DROP TABLE IF EXISTS projects_with_indx;
            - DROP TABLE IF EXISTS dept_with_indx;
            - DROP TABLE IF EXISTS employees_without_indx;
            - DROP TABLE IF EXISTS projects_without_indx;
            - DROP TABLE IF EXISTS dept_without_indx;
        loadRules:
            - table: projects_with_indx
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: dept_id
                    util: RandomInt
                    params: [1, 10000]
            
            - table: projects_without_indx
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: dept_id
                    util: RandomInt
                    params: [1, 10000]

            - table: dept_with_indx
              rows: 10000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]

            - table: dept_without_indx
              rows: 10000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
              
            - table: employees_with_indx
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: dept_id
                    util: RandomInt
                    params: [1, 10000]

            - table: employees_without_indx
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: dept_id
                    util: RandomInt
                    params: [1, 10000]

        afterLoad:
            - ALTER TABLE projects_with_indx add CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES dept_with_indx(uid) on delete cascade on update cascade;
            - ALTER TABLE employees_with_indx add CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES dept_with_indx(uid) on delete cascade on update cascade;
            - ALTER TABLE projects_without_indx add CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES dept_without_indx(uid) on delete cascade on update cascade;
            - ALTER TABLE employees_without_indx add CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES dept_without_indx(uid) on delete cascade on update cascade;
            
        executeRules:
            - workload: select_with_indx
              run:
                  - name: select_with_indx
                    weight: 100
                    queries:
                        - query: SELECT * FROM dept_with_indx where uid=?;
                          bindings:
                              util: RandomNumber
                              params: [1, 10000]

            - workload: insert_with_indx
              run:
                  - name: insert_with_indx
                    weight: 100
                    queries:
                        - query: insert into dept_with_indx values(?,?,?);
                          bindings:
                              - count: 2
                                util: PrimaryIntGen
                                params: [10001, 900000]
                              - util: RandomAString
                                params: [1, 20]

            - workload: update_with_indx
              run:
                  - name: update_with_indx
                    weight: 100
                    queries:
                        - query: update dept_with_indx set uid=? where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 900000]
                            - util: PrimaryIntGen
                              params: [1, 900000]

            - workload: delete_with_indx
              run:
                  - name: delete_with_indx
                    weight: 100
                    queries:
                        - query: delete from dept_with_indx where uid=?
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 900000]
            
            - workload: select_without_indx
              run:
                  - name: select_without_indx
                    weight: 100
                    queries:
                        - query: SELECT * FROM dept_without_indx where uid=?;
                          bindings:
                              util: RandomNumber
                              params: [1, 10000]

            - workload: insert_without_indx
              run:
                  - name: insert_without_indx
                    weight: 100
                    queries:
                        - query: insert into dept_without_indx values(?,?,?);
                          bindings:
                              - count: 2
                                util: PrimaryIntGen
                                params: [10001, 900000]
                              - util: RandomAString
                                params: [1, 20]

            - workload: update_without_indx
              run:
                  - name: update_without_indx
                    weight: 100
                    queries:
                        - query: update dept_without_indx set uid=? where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 900000]
                            - util: PrimaryIntGen
                              params: [1, 900000]

            - workload: delete_without_indx
              run:
                  - name: delete_without_indx
                    weight: 100
                    queries:
                        - query: delete from dept_without_indx where uid=?
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 900000]