type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS employees;
            - DROP TABLE IF EXISTS projects;
            - DROP TABLE IF EXISTS dept;
            - create table dept(id int primary key, name varchar(20) not null);
            - create table projects(id int primary key, uid int unique, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table employees(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(8,2), project_id int not null, dept_id int not null);
        cleanup:
            - DROP TABLE IF EXISTS employees;
            - DROP TABLE IF EXISTS projects;
            - DROP TABLE IF EXISTS dept;
        loadRules:
            - table: projects
              rows: 10000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: employees
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomInt
                    params: [1,10000]
                  - name: dept_id
                    util: RandomInt
                    params: [1,10000]
              
            - table: dept
              rows: 10000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]

        afterLoad:
            - ALTER TABLE employees add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects(id);
            - ALTER TABLE employees add CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES dept(id);
            
        executeRules:
            - workload: select
              run:
                  - name: select
                    weight: 100
                    queries:
                        - query: SELECT * FROM employees where project_id=? or dept_id=?;
                          bindings:
                            - count: 2
                              util: RandomNumber
                              params: [1, 10000]

            - workload: insert
              run:
                  - name: insert
                    weight: 100
                    queries:
                        - query: insert into employees values(?,?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [100001, 900000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 100]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomInt
                                params: [1,10000]
                              - util: RandomInt
                                params: [1,10000]
            - workload: update
              run:
                  - name: update
                    weight: 100
                    queries:
                        - query: update employees set project_id=? and dept_id=? where id=?;
                          bindings:
                            - util: RandomInt
                              params: [1, 10000]
                            - util: RandomInt
                              params: [1, 10000]
                            - util: PrimaryIntGen
                              params: [1, 900000]