type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain: true
yaml_version: v1.0
targetCPU: 75
toleranceCPU: 5
optimalThreads: true
samplingTime: 180
useThroughputThreshold: true
scalingMinDeltaPercent: 3
restingTimeSecs: 180
works:
    work:
        time_secs: 900
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_MVI_10_col;
            - CREATE TABLE THRPT_MVI_10_col (dept_id INT, emp_id INT, payload1 TEXT, payload2 TEXT, payload3 TEXT, payload4 TEXT, payload5 TEXT, payload6 TEXT, payload7 TEXT, payload8 TEXT, payload9 TEXT, payload10 TEXT, PRIMARY KEY(dept_id ASC, emp_id ASC)) SPLIT AT VALUES ((4), (7));
        cleanup:
            - DROP TABLE IF EXISTS THRPT_MVI_10_col;
        iterationCleanup:
            - DROP TABLE IF EXISTS THRPT_MVI_10_col;
            - CREATE TABLE THRPT_MVI_10_col (dept_id INT, emp_id INT, payload1 TEXT, payload2 TEXT, payload3 TEXT, payload4 TEXT, payload5 TEXT, payload6 TEXT, payload7 TEXT, payload8 TEXT, payload9 TEXT, payload10 TEXT, PRIMARY KEY(dept_id ASC, emp_id ASC)) SPLIT AT VALUES ((4), (7));

        loadRules:
            - table: THRPT_MVI_10_col
              rows: 10000000
              columns:
                  - name: dept_id
                    util: RandomUniqueCyclicIntGen
                    params: [1,9,1]
                  - name: emp_id
                    util: PrimaryIntGenThroughput
                    params: [1, 10000000]
                  - name: payload
                    count: 10
                    util: RandomAString
                    params: [100, 100]

        executeRules:
            - workload: THRPT_multivalue_insert_10cols
              run:
                  - name: THRPT_multivalue_insert_10cols
                    weight: 100
                    queries:
                        - query: INSERT INTO THRPT_MVI_10_col VALUES [(?,?,?,?,?,?,?,?,?,?,?,?)][pattern_count]
                          pattern_count: 10
                          bindings:
                              - util: RandomUniqueCyclicIntGen
                                params: [1,9,1]
                              - util: PrimaryIntGenThroughput
                                params: [10000001, 2147483646]
                              - util: RandomAString
                                count: 10
                                params: [100, 100]