type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 5
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 120
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - ALTER DATABASE yugabyte SET yb_explicit_row_lock_skip_locked_max_read_ahead TO {{max_read_ahead}};
            - CREATE TABLE SL_jobs (id INT, status INT, priority INT, created_at TIMESTAMP, payload TEXT, primary key (id asc)) split at values ((333333), (666666));

        cleanup:
            - ALTER DATABASE yugabyte SET yb_explicit_row_lock_skip_locked_max_read_ahead TO DEFAULT;
            - DROP TABLE IF EXISTS SL_jobs;

        loadRules:
            - table: SL_jobs
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: status
                    util: CyclicSeqIntGen
                    params: [1, 10]
                  - name: priority
                    util: RandomInt
                    params: [1, 100]
                  - name: created_at
                    util: RandomTimestamp
                    params: [10000000]
                  - name: payload
                    util: RandomAString
                    params: [1000, 1000]

        executeRules:
            - workload: SL1_limit_without_contention
              run:
                  - name: no_contention_queries
                    weight: 100
                    queries:
                        - query: SELECT * FROM SL_jobs where status = ? and id between ? and ? FOR UPDATE SKIP LOCKED LIMIT 100;
                          bindings:
                              - util: RandomInt
                                params: [1, 10]
                              - util: RangeDivider
                                params: [1000000]
                                referenceName: start_range
                              - util: ExpressionEval
                                params: ["start_range + 199999"]

            - workload: SL1_limit_with_20%_contention
              run:
                  - name: contention_queries
                    weight: 20
                    queries:
                        - query: SELECT * FROM SL_jobs where status = 1 and id between 1 and 100000 FOR UPDATE SKIP LOCKED LIMIT 100;

                  - name: no_contention_queries
                    weight: 80
                    queries:
                        - query: SELECT * FROM SL_jobs where status = ? and id between ? and ? FOR UPDATE SKIP LOCKED LIMIT 100;
                          bindings:
                              - util: RandomInt
                                params: [2, 10]
                              - util: RangeDivider
                                params: [1000000]
                                referenceName: start_range
                              - util: ExpressionEval
                                params: ["start_range + 199999"]

            - workload: SL1_limit_with_40%_contention
              run:
                  - name: contention_queries
                    weight: 40
                    queries:
                        - query: SELECT * FROM SL_jobs where status = 1 and id between 1 and 100000 FOR UPDATE SKIP LOCKED LIMIT 100;

                  - name: no_contention_queries
                    weight: 60
                    queries:
                        - query: SELECT * FROM SL_jobs where status = ? and id between ? and ? FOR UPDATE SKIP LOCKED LIMIT 100;
                          bindings:
                              - util: RandomInt
                                params: [2, 10]
                              - util: RangeDivider
                                params: [1000000]
                                referenceName: start_range
                              - util: ExpressionEval
                                params: ["start_range + 199999"]

            - workload: SL1_limit_with_60%_contention
              run:
                  - name: contention_queries
                    weight: 60
                    queries:
                        - query: SELECT * FROM SL_jobs where status = 1 and id between 1 and 100000 FOR UPDATE SKIP LOCKED LIMIT 100;

                  - name: no_contention_queries
                    weight: 40
                    queries:
                        - query: SELECT * FROM SL_jobs where status = ? and id between ? and ? FOR UPDATE SKIP LOCKED LIMIT 100;
                          bindings:
                              - util: RandomInt
                                params: [2, 10]
                              - util: RangeDivider
                                params: [1000000]
                                referenceName: start_range
                              - util: ExpressionEval
                                params: ["start_range + 199999"]

            - workload: SL1_limit_with_80%_contention
              run:
                  - name: contention_queries
                    weight: 80
                    queries:
                        - query: SELECT * FROM SL_jobs where status = 1 and id between 1 and 100000 FOR UPDATE SKIP LOCKED LIMIT 100;

                  - name: no_contention_queries
                    weight: 20
                    queries:
                        - query: SELECT * FROM SL_jobs where status = ? and id between ? and ? FOR UPDATE SKIP LOCKED LIMIT 100;
                          bindings:
                              - util: RandomInt
                                params: [2, 10]
                              - util: RangeDivider
                                params: [1000000]
                                referenceName: start_range
                              - util: ExpressionEval
                                params: ["start_range + 199999"]

            - workload: SL1_limit_with_100%_contention
              run:
                  - name: contention_queries
                    weight: 100
                    queries:
                        - query: SELECT * FROM SL_jobs where status = 1 and id between 1 and 100000 FOR UPDATE SKIP LOCKED LIMIT 100;