type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
use_dist_in_explain : true
works:
    work:
        time_secs: 300
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS Indexed1M_1;
            - CREATE TABLE Indexed1M_1(col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_bigint_id_4 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1));
            - CREATE INDEX ON Indexed1M_1(col_bigint_id_2);
            - CREATE INDEX ON Indexed1M_1(col_bigint_id_4 ASC);

        cleanup:
            - DROP TABLE IF EXISTS Indexed1M_1;

        loadRules:
              - table: Indexed1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 4
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 2
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]

        executeRules:
            - workload: AGGRG9_count_bigint_non_indexed_column
              customTags: schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,aggregateon=nonindexed
              run:
                  - name: count_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select count(col_bigint_id_3) from Indexed1M_1
            - workload: AGGRG9_count_bigint_hash_pkey_column
              customTags: schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,aggregateon=rangepkey
              run:
                  - name: count_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select count(col_bigint_id_1) from Indexed1M_1
            - workload: AGGRG9_count_bigint_hash_pkey_column_with_filter
              customTags: schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,filtercount=one,aggregateon=hashpkey,filteron=rangepkey,filtertype=comparision
              run:
                  - name: count_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select count(col_bigint_id_1) from Indexed1M_1 where col_bigint_id_1>1
            - workload: AGGRG9_count_bigint_hash_secondary_indexed_column
              customTags: schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,aggregateon=rangeskey
              run:
                  - name: count_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select count(col_bigint_id_2) from Indexed1M_1
            - workload: AGGRG9_count_bigint_hash_secondary_indexed_column_with_filter
              customTags: schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,filtercount=one,aggregateon=rangeskey,filteron=rangeskey,filtertype=comparision
              run:
                  - name: count_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select count(col_bigint_id_2) from Indexed1M_1 where col_bigint_id_2>1
            -   workload: AGGRG9_count_bigint_range_secondary_indexed_column
                customTags: customer=1,schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,aggregateon=rangeskey
                run:
                    -   name: count_bigint_non_indexed_column
                        weight: 100
                        queries:
                            -   query: select count(col_bigint_id_4) from Indexed1M_1
            -   workload: AGGRG9_count_bigint_range_secondary_indexed_column_with_filter
                customTags: customer=1,schematype=colocated,partition=range,aggregate=count,cardinality=single,projection=aggregate,filtercount=one,aggregateon=rangeskey,filteron=rangeskey,filtertype=comparision
                run:
                    -   name: count_bigint_non_indexed_column
                        weight: 100
                        queries:
                            -   query: select count(col_bigint_id_4) from Indexed1M_1 where col_bigint_id_4>1