type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_G2_payments;
            - CREATE TABLE THRPT_G2_payments(payment_id BIGSERIAL, txn_id BIGINT, user_id BIGINT, merchant_id BIGINT, amount INT, status INT, created_at TIMESTAMP, updated_at TIMESTAMP, PRIMARY KEY(payment_id ASC)) SPLIT AT VALUES ((333333), (666666));
            - CREATE INDEX idx_payments_txn_covering ON THRPT_G2_payments (txn_id ASC) INCLUDE (amount, status, user_id) SPLIT AT VALUES ((333333), (666666));

        cleanup:
            - DROP TABLE IF EXISTS THRPT_G2_payments;

        loadRules:
            - table: THRPT_G2_payments
              rows: 1000000
              columns:
                  - name: payment_id
                    util: RandomUniqueIntGen
                    params: [1, 1000000]
                  - name: txn_id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: user_id
                    util: RandomNumber
                    params: [1, 100000]
                  - name: merchant_id
                    util: RandomNumber
                    params: [1, 10000]
                  - name: amount
                    util: RandomNumber
                    params: [1, 100000]
                  - name: status
                    util: RandomNumber
                    params: [1, 5]
                  - name: created_at
                    util: RandomTimestamp
                    params: [10000000]
                  - name: updated_at
                    util: RandomTimestamp
                    params: [10000000]

        executeRules:
            - workload: THRPT_G2_index_BETWEEN
              run:
                  - name: THRPT_G2_index_BETWEEN
                    weight: 100
                    queries:
                        - query: SELECT * FROM THRPT_G2_payments WHERE txn_id BETWEEN ? AND ?;
                          bindings:
                              -   util: RandomNumber
                                  params: [1, 990000]
                                  referenceName: txn_id_1
                              -   util: ExpressionEval
                                  params:
                                      - "txn_id_1 + 10000"
