type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain: true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_G7_user_activity;
            - CREATE TABLE THRPT_G7_user_activity (activity_id BIGINT, segment_id INT, user_id INT, action_type TEXT, event_time TIMESTAMP, metadata TEXT, PRIMARY KEY(activity_id ASC));
            - CREATE INDEX idx_user_activity_feed ON THRPT_G7_user_activity(segment_id ASC, event_time DESC) INCLUDE (user_id, action_type);
        cleanup:
            - DROP TABLE IF EXISTS THRPT_G7_user_activity;

        loadRules:
            - table: THRPT_G7_user_activity
              rows: 1000000
              columns:
                  - name: activity_id
                    util: RandomUniqueIntGen
                    params: [1, 1000000]
                  - name: segment_id
                    util: CyclicSeqIntGen
                    params: [1, 10000]
                  - name: user_id
                    util: CyclicSeqIntGen
                    params: [1, 100000]
                  - name: action_type
                    util: RandomAString
                    params: [10, 10]
                  - name: event_time
                    util: RandomTimestamp
                    params: [10000000]
                  - name: metadata
                    util: RandomAString
                    params: [1000, 1000]

        executeRules:
            - workload: THRPT_G7_idx_backward_scan
              run:
                  - name: THRPT_G7_idx_backward_scan
                    weight: 100
                    queries:
                        - query: SELECT activity_id, user_id, action_type, event_time FROM THRPT_G7_user_activity WHERE segment_id = ? ORDER BY event_time ASC limit 50;
                          bindings:
                              - util: RandomInt
                                params: [1, 10000]
