type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
username: {{ username }}
password: {{ password }}
isolation: TRANSACTION_REPEATABLE_READ
batchsize: 128
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: 2.0
yaml_change_description: Correcting data distribution to remove variation
works:
    work:
        time_secs: 120
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
          - DROP TABLE IF EXISTS pkeyBigint1M_1;
          - DROP TABLE IF EXISTS pkeyBigint1M_2;
          - DROP TABLE IF EXISTS pkeyBigint1M_3;
          - CREATE TABLE pkeyBigint1M_1(col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1, col_bigint_id_2, col_bigint_id_3, col_bigint_card1_1));
          - CREATE TABLE pkeyBigint1M_2(col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1, col_bigint_id_2, col_bigint_id_3, col_bigint_card1_1));
          - CREATE TABLE pkeyBigint1M_3(col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1, col_bigint_id_2, col_bigint_id_3, col_bigint_card1_1));
          - CREATE INDEX ON pkeyBigint1M_1(col_bigint_card2_1);
          - CREATE INDEX ON pkeyBigint1M_2(col_bigint_card2_1);
          - CREATE INDEX ON pkeyBigint1M_3(col_bigint_card2_1);

        cleanup:
            - DROP TABLE IF EXISTS pkeyBigint1M_1;
            - DROP TABLE IF EXISTS pkeyBigint1M_2;
            - DROP TABLE IF EXISTS pkeyBigint1M_3;
        loadRules:
              - table: pkeyBigint1M_
                count: 3
                rows: 1000000
                columns:
                    - name: col_bigint_card1_
                      count: 1
                      util: CyclicSeqIntGen
                      params: [ 1000001, 1001000 ]
                    - name: col_bigint_card2_
                      count: 1
                      util: CyclicSeqIntGen
                      params: [ 1000001, 1010000]
                    - name: col_bigint_card3_
                      count: 1
                      util: CyclicSeqIntGen
                      params: [ 1000001, 1000100 ]
                    - name: col_bigint_id_
                      count: 3
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: RandomAString
                      params: [10, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: RandomAString
                      params: [100, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: RandomAString
                      params: [500, 500]

        executeRules:
            -   workload: JOING10_1_join_on_2tbls_withfilter_onpkey_grpby_1col
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_3tbl
                        weight: 100
                        queries:
                            -   query: select a.col_bigint_card2_1, count(a.col_bigint_id_1), count(b.col_bigint_id_1) from pkeyBigint1M_1 as a,pkeyBigint1M_2 as b where a.col_bigint_card1_1 in (?) and a.col_bigint_id_1=b.col_bigint_id_1  GROUP BY a.col_bigint_card2_1
                                bindings:
                                    - util: RandomUniqueCyclicIntGen
                                      params: [ 1000001, 1001000 ]

            - workload: JOING10_2_join_on_3tbls_withfilter_onpkey_grpby_2col
              customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
              run:
                  - name: join_on_pk_3tbl
                    weight: 100
                    queries:
                        - query: select a.col_bigint_card2_1, a.col_bigint_card2_1, count(b.col_bigint_id_1) from pkeyBigint1M_1 as a,pkeyBigint1M_2 as b,pkeyBigint1M_3 as c where a.col_bigint_card2_1 in (?) and a.col_bigint_id_1=b.col_bigint_id_1 and a.col_bigint_id_1=c.col_bigint_id_1  GROUP BY a.col_bigint_card2_1,a.col_bigint_card1_1
                          bindings:
                              - util: RandomUniqueCyclicIntGen
                                params: [ 1000001, 1010000 ]

            -   workload: JOING10_3_join_on_2tbls_withfilter_onpkey_grpby_2col
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_3tbl
                        weight: 100
                        queries:
                            -   query: select a.col_bigint_card2_1, count(a.col_bigint_id_1), count(b.col_bigint_id_1) from pkeyBigint1M_1 as a,pkeyBigint1M_2 as b where a.col_bigint_card2_1 in (?) and a.col_bigint_id_1=b.col_bigint_id_1  GROUP BY a.col_bigint_card2_1
                                bindings:
                                    - util: RandomUniqueCyclicIntGen
                                      params: [ 1000001, 1010000 ]


            -   workload: JOING10_4_join_on_2tbls_withfilter_onpkey_ordby_1col
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_3tbl
                        weight: 100
                        queries:
                            -   query: select pkeyBigint1M_1.col_bigint_id_1, pkeyBigint1M_2.col_bigint_id_1 from pkeyBigint1M_1,pkeyBigint1M_2 where pkeyBigint1M_1.col_bigint_card1_1 in (?) and pkeyBigint1M_1.col_bigint_id_1=pkeyBigint1M_2.col_bigint_id_1 ORDER BY pkeyBigint1M_1.col_bigint_card1_1
                                bindings:
                                    - util: RandomUniqueCyclicIntGen
                                      params: [ 1000001, 1001000 ]

            - workload: JOING10_5_join_on_3tbls_withfilter_onpkey_ordby_1col
              customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
              run:
                  - name: join_on_pk_3tbl
                    weight: 100
                    queries:
                        - query: select pkeyBigint1M_1.col_bigint_id_1, pkeyBigint1M_2.col_bigint_id_1, pkeyBigint1M_3.col_bigint_id_1 from pkeyBigint1M_1,pkeyBigint1M_2,pkeyBigint1M_3 where pkeyBigint1M_1.col_bigint_card1_1 in (?) and pkeyBigint1M_1.col_bigint_id_1=pkeyBigint1M_2.col_bigint_id_1 and pkeyBigint1M_1.col_bigint_id_1=pkeyBigint1M_3.col_bigint_id_1 ORDER BY pkeyBigint1M_1.col_bigint_card1_1
                          bindings:
                              - util: RandomUniqueCyclicIntGen
                                params: [ 1000001, 1001000 ]

            -   workload: JOING10_6_join_on_2tbls_withfilter_onpkey_ordby_2col
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_3tbl
                        weight: 100
                        queries:
                            -   query: select pkeyBigint1M_1.col_bigint_id_1, pkeyBigint1M_2.col_bigint_id_1 from pkeyBigint1M_1,pkeyBigint1M_2 where pkeyBigint1M_1.col_bigint_card1_1 in (?) and pkeyBigint1M_1.col_bigint_id_1=pkeyBigint1M_2.col_bigint_id_1 ORDER BY pkeyBigint1M_1.col_bigint_card1_1,pkeyBigint1M_1.col_bigint_card2_1
                                bindings:
                                    - util: RandomUniqueCyclicIntGen
                                      params: [ 1000001, 1001000 ]

            -   workload: JOING10_7_join_on_2tbls_withfilter_onpkey_ordby_desc_1col
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projectition=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_3tbl
                        weight: 100
                        queries:
                        -   query: select pkeyBigint1M_1.col_bigint_id_1, pkeyBigint1M_2.col_bigint_id_1 from pkeyBigint1M_1,pkeyBigint1M_2 where pkeyBigint1M_1.col_bigint_card1_1 in (?) and pkeyBigint1M_1.col_bigint_id_1=pkeyBigint1M_2.col_bigint_id_1 ORDER BY pkeyBigint1M_1.col_bigint_card1_1 DESC
                            bindings:
                                - util: RandomUniqueCyclicIntGen
                                  params: [ 1000001, 1001000 ]