type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {{username}}
password: {{password}}
batchsize: 1
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 4
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain: true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_in_100kb_row;
            - CREATE TABLE THRPT_in_100kb_row (id INT, lookup_key INT, payload TEXT, PRIMARY KEY(id asc)) SPLIT AT VALUES ((33333), (66666));

        cleanup:
            - DROP TABLE IF EXISTS THRPT_in_100kb_row;

        loadRules:
            - table: THRPT_in_100kb_row
              rows: 100000
              columns:
                  - name: id
                    util: RandomUniqueIntGen
                    params: [1, 100000]
                  - name: lookup_key
                    util: RandomUniqueIntGen
                    params: [1, 100000]
                  - name: payload
                    util: RandomAString
                    params: [102400, 102400]
        executeRules:
            - workload: THRPT_seek_1col_100KB_row_pk_in_1K_values
              run:
                  - name: THRPT_seek_1col_100KB_row_pk_in_1K_values
                    weight: 100
                    queries:
                        - query: SELECT * FROM THRPT_in_100kb_row WHERE id IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);
                          bindings:
                              - util: RandomNumber
                                count: 100
                                params: [1, 100000]
