type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {{username}}
password: {{password}}
batchsize: 1
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain: true
yaml_version: v1.0
targetCPU: 75
toleranceCPU: 5
optimalThreads: true
samplingTime: 120
time: 600
useThroughputThreshold: true
truncateBetweenIterations: true
works:
    work:
        time_secs: 180
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_MVI_1;
            - CREATE TABLE THRPT_MVI_1 (k INTEGER, id INTEGER, c CHAR(120), pad CHAR(60), PRIMARY KEY (k ASC, id ASC)) SPLIT AT VALUES ((3), (6));
        cleanup:
            - DROP TABLE IF EXISTS THRPT_MVI_1;

        iterationCleanup:
            - DROP TABLE IF EXISTS THRPT_MVI_1;
            - CREATE TABLE THRPT_MVI_1 (k INTEGER, id INTEGER, c CHAR(120), pad CHAR(60), PRIMARY KEY (k ASC, id ASC)) SPLIT AT VALUES ((3), (6));

        loadRules:
            - table: THRPT_MVI_1
              rows: 1000000
              columns:
                  - name: k
                    util: RandomUniqueCyclicIntGen
                    params: [1, 9, 1]
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: c
                    util: RandomAString
                    params: [120, 120]
                  - name: pad
                    util: RandomAString
                    params: [60, 60]

        executeRules:
            - workload: THRPT_multivalue_insert_1row
              run:
                  - name: THRPT_multivalue_insert_1row
                    weight: 100
                    queries:
                        - query: INSERT INTO THRPT_MVI_1 VALUES [(?,?,?,?)][pattern_count]
                          pattern_count: 1
                          bindings:
                              - util: RandomUniqueCyclicIntGen
                                params: [1, 9, 1]
                              - util: PrimaryIntGenThroughput
                                params: [1, 1000000000]
                              - util: RandomAString
                                params: [120, 120]
                              - util: RandomAString
                                params: [60, 60]
