#100000	col1	col2	    col3      col4
#Table1	1*1M	1000*1k	    10000*100

#TEST FOR YUGABYTE REGULAR TABLES
#GOAL7 Orderby on hash partitioned table
#Orderby clause on non indexed column of bigint datatype
#Orderby clause on hash pkey of bigint datatype
#Orderby clause on hash secondary indexed column of bigint datatype
#Orderby clause on range secondary indexed column of bigint datatype
type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.1
use_dist_in_explain : true
works:
    work:
        time_secs: 120
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true

        create:
            - DROP TABLE IF EXISTS Indexed1M_1;
            - CREATE TABLE Indexed1M_1(col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_bigint_id_4 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_card1_1, col_bigint_card2_1, col_bigint_card3_1, col_bigint_id_1));
            - CREATE INDEX ON Indexed1M_1(col_bigint_id_2);
            - CREATE INDEX ON Indexed1M_1(col_bigint_id_3 ASC);

        cleanup:
            - DROP TABLE IF EXISTS Indexed1M_1;

        loadRules:
              - table: Indexed1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_card1_
                      count: 1
                      util: OneNumberFromArray
                      params: [ 1000000 ]
                    - name: col_bigint_card2_
                      count: 1
                      util: RandomInt
                      params: [ 1000001, 1001000 ]
                    - name: col_bigint_card3_
                      count: 1
                      util: RandomInt
                      params: [ 1000001, 1010001 ]
                    - name: col_bigint_id_
                      count: 4
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]

        executeRules:
            - workload: ORDG7_ordby_bigint_non_indexed_column
              customTags: customer=2,schematype=regular,partition=hash,cardinality=single,projection=nonindexed,queryshape=orderby,orderbyon=nonindexed
              run:
                  - name: ordby_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_4 from Indexed1M_1 order by col_bigint_id_4
            - workload: ORDG7_ordby_bigint_hash_pkey_column
              customTags: customer=2,schematype=regular,partition=hash,pkey=hash,cardinality=single,projection=hashpkey,queryshape=orderby,orderbyon=hashpkey
              run:
                  - name: ordby_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 order by col_bigint_id_1
            - workload: ORDG7_ordby_bigint_hash_pkey_with_filter_column
              customTags: customer=1,schematype=regular,partition=hash,pkey=hash,cardinality=single,projection=hashpkey,filtercount=one,filteron=hashpkey,filtertype=comparision,queryshape=orderby,orderbyon=hashpkey
              run:
                  - name: yb_ordby_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 where col_bigint_id_1>1 order by col_bigint_id_1
            - workload: ORDG7_ordby_bigint_hash_secondary_indexed_column
              customTags: schematype=regular,partition=hash,skey=hash,cardinality=single,projection=hashskey,queryshape=orderby,orderbyon=hashskey
              run:
                  - name: ordby_bigint_secondary_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_2 from Indexed1M_1 order by col_bigint_id_2
            - workload: ORDG7_ordby_bigint_hash_secondary_indexed_with_filter_column
              customTags: customer=1,schematype=regular,partition=hash,skey=hash,cardinality=single,projection=hashskey,filtercount=one,filteron=hashskey,filtertype=comparision,queryshape=orderby,orderbyon=hashskey
              run:
                  - name: yb_ordby_bigint_secondary_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_2 from Indexed1M_1 where col_bigint_id_2>1 order by col_bigint_id_2
            - workload: ORDG7_ordby_bigint_range_secondary_indexed_column
              customTags: schematype=regular,partition=hash,skey=asc,cardinality=single,projection=indexed,queryshape=orderby,orderbyon=rangeskey
              run:
                  - name: ordby_bigint_secondary_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_3 from Indexed1M_1 order by col_bigint_id_3
            - workload: ORDG7_ordby_bigint_range_secondary_indexed_with_filter_column
              customTags: customer=1,schematype=regular,partition=hash,skey=asc,cardinality=single,projection=indexed,filtercount=one,filteron=rangeskey,filtertype=comparision,queryshape=orderby,orderbyon=rangeskey
              run:
                  - name: yb_ordby_bigint_secondary_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_3 from Indexed1M_1 where col_bigint_id_3>1 order by col_bigint_id_3

            - workload: ORDG7_ordby_bigint_hash_pkey_with_filter_column_desc
              customTags: customer=1,schematype=regular,partition=hash,pkey=composite,cardinality=multiple,projection=hashpkey,filtercount=one,filteron=hashpkey,filtertype=comparision,queryshape=orderby,orderbyon=hashpkeydesc
              run:
                  - name: ordby_bigint_hash_pkey_with_filter_column_desc
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 where col_bigint_id_1>1 order by col_bigint_id_1 DESC

            - workload: ORDG7_ordby_bckwrd_ind_scan_pkey_filter
              customTags: customer=0,schematype=regular,partition=hash,pkey=composite,cardinality=multiple,projection=hashpkey,filtercount=one,filteron=hashpkey,filtertype=comparision,queryshape=orderby,orderbyon=hashpkeydesc
              run:
                  - name: ordby_bckwrd_ind_scan_pkey_filter
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 where col_bigint_card1_1=1000000 and col_bigint_card2_1<1000010 order by col_bigint_card2_1 DESC

            - workload: ORDG7_ordby_fwd_ind_scan_pkey_filter
              customTags: customer=0,schematype=regular,partition=hash,pkey=composite,cardinality=multiple,projection=hashpkey,filtercount=one,filteron=hashpkey,filtertype=comparision,queryshape=orderby,orderbyon=hashpkeydesc
              run:
                  - name: ordby_fwd_ind_scan_pkey_filter
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 where col_bigint_card1_1=1000000 and col_bigint_card2_1<1000010 order by col_bigint_card2_1

            - workload: ORDG7_ordby_bckwrd_ind_scan_pkey_filter_full_tbl
              customTags: customer=0,schematype=regular,partition=hash,pkey=composite,cardinality=multiple,projection=hashpkey,filtercount=one,filteron=hashpkey,filtertype=comparision,queryshape=orderby,orderbyon=hashpkeydesc
              run:
                  - name: ordby_bckwrd_ind_scan_pkey_filter_full_tbl
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 where col_bigint_card1_1=1000000 and col_bigint_card3_1>1 order by col_bigint_card3_1 DESC

            - workload: ORDG7_ordby_fwd_ind_scan_pkey_filter_full_tbl
              customTags: customer=0,schematype=regular,partition=hash,pkey=composite,cardinality=multiple,projection=hashpkey,filtercount=one,filteron=hashpkey,filtertype=comparision,queryshape=orderby,orderbyon=hashpkeydesc
              run:
                  - name: ordby_fwd_ind_scan_pkey_filter_full_tbl
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 where col_bigint_card1_1=1000000 and col_bigint_card3_1>1 order by col_bigint_card3_1