type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/test_db?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
works:
    work:
        time: 10
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBMicroBenchmarkImplementation
    properties:
        create:
            - DROP TABLE IF EXISTS accounts;
            - CREATE TABLE accounts (id int NOT NULL, name varchar(64) NOT NULL, CONSTRAINT pk_accounts PRIMARY KEY (id));
            - CREATE INDEX idx_accounts_name ON accounts (name);
        loadRules:
            -   table: accounts
                rows: 100
                columns:
                    - name : id
                      util : PrimaryIntGen
                      params :
                          - 1
                          - 100
                    - name : name
                      util : RandomStringNumeric
                      params:
                          - 10
#        executeRules:
#            -   transaction_name: Account_query
#                weight: 100
#                queries:
#                    - query: SELECT * FROM accounts WHERE id > ?
#                      utils :
#                          - name:   RowRandomBoundedInt
#                            params:
#                                - 5
#                                - 10
#        cleanup:
#            - DROP TABLE accounts;