type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
works:
    work:
        time_secs: 5
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table if exists t1;
            - drop table if exists t2;
            - create table t1 (c1 int primary key, c2 int, c3 int, c4 text);
            - insert into t1 select i, i % 10, i % 12, lpad(i::text, 80, '#') from generate_series(1, 10000) i;
            - create index on t1 (c3 asc, c2 asc);
            - create table t2 (c1 int primary key, c2 int, c3 int, c4 text);
            - create index on t2 (c2);
        executeRules:
            -   workload: explainDistTesting
                run:
                    - name: DistTesting
                      weight: 100
                      queries:
                          - query: select * from t1 where c1 <= 123 and c2 = c3;