benchmarks:
    - name: perf-featurebench
      workloadSpec:
          type: featurebench
          properties:
              create: false
              load: false
              execute: false
              client-instance-type: c5.large
              benchbase-repo-branch: master
              test-user: sagarwal
              yaml-relative-path: config/yugabyte/scan_workloads/yugabyte/scanG4_yb_pkey_rangeScan_INclause_increasingRows_.yaml
              yb_owner: perf-team
      clusterSpec:
          platformId: 301
          #Template has ysql auth enabled . Password is Password@321
          templateName: m6i_8core_3node_1az_secure
          properties:
              ybSoftwareVersion: 2.17.1.0-b44
              # Review the gflags with actual before using in this yaml.
              masterGFlags:
                  - "name": "enable_automatic_tablet_splitting"
                    "value": true
                  - "name": "ysql_enable_packed_row"
                    "value": true
              #          - "name": "ysql_yb_enable_expression_pushdown"
              #            "value": true
              tserverGFlags:
                  - "name": "enable_automatic_tablet_splitting"
                    "value": true
                  - "name": "ysql_enable_packed_row"
                    "value": true
          #       - "name": "ysql_yb_enable_expression_pushdown"
          #          "value": true
      jobGroup:
          - name: featurebench
            numClusters: 1
            reuse: true
            clusterSpec:
                overrides: {}
            workloadSpec:
                overrides: {}