type: postgres
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 4
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
targetCPU: 80
toleranceCPU: 5
optimalThreads: true
samplingTime: 180
useThroughputThreshold: true
restingTimeSecs: 360
works:
    work:
        time_secs: 900
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS THRPT_MVI_100_col;
            - CREATE TABLE THRPT_MVI_100_col (dept_id INT, emp_id INT, payload1 TEXT, payload2 TEXT, payload3 TEXT, payload4 TEXT, payload5 TEXT, payload6 TEXT, payload7 TEXT, payload8 TEXT, payload9 TEXT, payload10 TEXT, payload11 TEXT, payload12 TEXT, payload13 TEXT, payload14 TEXT, payload15 TEXT, payload16 TEXT, payload17 TEXT, payload18 TEXT, payload19 TEXT, payload20 TEXT, payload21 TEXT, payload22 TEXT, payload23 TEXT, payload24 TEXT, payload25 TEXT, payload26 TEXT, payload27 TEXT, payload28 TEXT, payload29 TEXT, payload30 TEXT, payload31 TEXT, payload32 TEXT, payload33 TEXT, payload34 TEXT, payload35 TEXT, payload36 TEXT, payload37 TEXT, payload38 TEXT, payload39 TEXT, payload40 TEXT, payload41 TEXT, payload42 TEXT, payload43 TEXT, payload44 TEXT, payload45 TEXT, payload46 TEXT, payload47 TEXT, payload48 TEXT, payload49 TEXT, payload50 TEXT, payload51 TEXT, payload52 TEXT, payload53 TEXT, payload54 TEXT, payload55 TEXT, payload56 TEXT, payload57 TEXT, payload58 TEXT, payload59 TEXT, payload60 TEXT, payload61 TEXT, payload62 TEXT, payload63 TEXT, payload64 TEXT, payload65 TEXT, payload66 TEXT, payload67 TEXT, payload68 TEXT, payload69 TEXT, payload70 TEXT, payload71 TEXT, payload72 TEXT, payload73 TEXT, payload74 TEXT, payload75 TEXT, payload76 TEXT, payload77 TEXT, payload78 TEXT, payload79 TEXT, payload80 TEXT, payload81 TEXT, payload82 TEXT, payload83 TEXT, payload84 TEXT, payload85 TEXT, payload86 TEXT, payload87 TEXT, payload88 TEXT, payload89 TEXT, payload90 TEXT, payload91 TEXT, payload92 TEXT, payload93 TEXT, payload94 TEXT, payload95 TEXT, payload96 TEXT, payload97 TEXT, payload98 TEXT, payload99 TEXT, payload100 TEXT, PRIMARY KEY(dept_id, emp_id));
        cleanup:
            - DROP TABLE IF EXISTS THRPT_MVI_100_col;

        iterationCleanup:
            - DROP TABLE IF EXISTS THRPT_MVI_100_col;
            - CREATE TABLE THRPT_MVI_100_col (dept_id INT, emp_id INT, payload1 TEXT, payload2 TEXT, payload3 TEXT, payload4 TEXT, payload5 TEXT, payload6 TEXT, payload7 TEXT, payload8 TEXT, payload9 TEXT, payload10 TEXT, payload11 TEXT, payload12 TEXT, payload13 TEXT, payload14 TEXT, payload15 TEXT, payload16 TEXT, payload17 TEXT, payload18 TEXT, payload19 TEXT, payload20 TEXT, payload21 TEXT, payload22 TEXT, payload23 TEXT, payload24 TEXT, payload25 TEXT, payload26 TEXT, payload27 TEXT, payload28 TEXT, payload29 TEXT, payload30 TEXT, payload31 TEXT, payload32 TEXT, payload33 TEXT, payload34 TEXT, payload35 TEXT, payload36 TEXT, payload37 TEXT, payload38 TEXT, payload39 TEXT, payload40 TEXT, payload41 TEXT, payload42 TEXT, payload43 TEXT, payload44 TEXT, payload45 TEXT, payload46 TEXT, payload47 TEXT, payload48 TEXT, payload49 TEXT, payload50 TEXT, payload51 TEXT, payload52 TEXT, payload53 TEXT, payload54 TEXT, payload55 TEXT, payload56 TEXT, payload57 TEXT, payload58 TEXT, payload59 TEXT, payload60 TEXT, payload61 TEXT, payload62 TEXT, payload63 TEXT, payload64 TEXT, payload65 TEXT, payload66 TEXT, payload67 TEXT, payload68 TEXT, payload69 TEXT, payload70 TEXT, payload71 TEXT, payload72 TEXT, payload73 TEXT, payload74 TEXT, payload75 TEXT, payload76 TEXT, payload77 TEXT, payload78 TEXT, payload79 TEXT, payload80 TEXT, payload81 TEXT, payload82 TEXT, payload83 TEXT, payload84 TEXT, payload85 TEXT, payload86 TEXT, payload87 TEXT, payload88 TEXT, payload89 TEXT, payload90 TEXT, payload91 TEXT, payload92 TEXT, payload93 TEXT, payload94 TEXT, payload95 TEXT, payload96 TEXT, payload97 TEXT, payload98 TEXT, payload99 TEXT, payload100 TEXT, PRIMARY KEY(dept_id, emp_id));

        loadRules:
            - table: THRPT_MVI_100_col
              rows: 10000000
              columns:
                  - name: dept_id
                    util: RandomUniqueCyclicIntGen
                    params: [1,9,1]
                  - name: emp_id
                    util: PrimaryIntGenThroughput
                    params: [1, 10000000]
                  - name: payload
                    count: 100
                    util: RandomAString
                    params: [10, 10]

        executeRules:
            - workload: THRPT_multivalue_insert_100cols
              run:
                  - name: THRPT_multivalue_insert_100cols
                    weight: 100
                    queries:
                        - query: INSERT INTO THRPT_MVI_100_col VALUES [(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)][pattern_count]
                          pattern_count: 10
                          bindings:
                              - util: RandomUniqueCyclicIntGen
                                params: [1,9,1]
                              - util: PrimaryIntGenThroughput
                                params: [10000001, 2147483646]
                              - util: RandomAString
                                count: 100
                                params: [10, 10]