type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/test_db?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
works:
    work:
        serial: true
        active_terminals: 1
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        tableName: accounts
        columns: 10
        rows: 100
        indexes: 2
        filePath: accounts.csv
        rowsPerTransaction: 2000
        create:
            - DROP TABLE IF EXISTS t1;
            - CREATE TABLE t1 (k1 int,k2 text,v1 int,v2 text,PRIMARY KEY(k1 ASC, k2 ASC));
            - CREATE INDEX ON t1(v1 ASC, k2 ASC);
        cleanup:
            - DROP TABLE t1;
        loadRules:
            - table: t1
              rows: 1000
              columns:
                  - name: k1
                    util: RandomInt
                    params:
                        - 100
                        - 500
                  - name: k2
                    util: RandomAstring
                    params:
                        - 2
                        - 5
                  - name: v1
                    util: RandomInt
                    params:
                        - 5
                        - 6
                  - name: v2
                    util: RandomAString
                    params:
                        - 2
                        - 5
