type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/test_db?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
works:
    work:
        time_secs: 10
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.PointQuery
    properties:

