type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/test_db?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        create:
            - DROP TABLE IF EXISTS accounts;
            - CREATE TABLE accounts (id int NOT NULL, name varchar(64) NOT NULL, CONSTRAINT pk_accounts PRIMARY KEY (id));
            - CREATE INDEX idx_accounts_name ON accounts (name);
        cleanup:
            - DROP TABLE accounts;
        loadRules:
            - table: accounts
              rows: 1000
              columns:
                  -   name: id
                      util: PrimaryIntGen
                      params:
                          - 1
                          - 1000
                  -   name: name
                      util: RandomStringNumeric
                      params:
                          - 16
        executeRules:
            - workload: AccountQuery
              run:
                  -   name: selectQuery
                      weight: 100
                      queries:
                          -   query: SELECT * FROM accounts WHERE id > ?
                              bindings:
                                  -   util: RandomNumber
                                      params:
                                          - 1
                                          - 100

