type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/test_db?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 6
terminals: 6
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.CopyCommandBenchmark
    properties:
        rows: 100
        columns: 10
        indexes: 2
        rowspertransaction: 1000
#        tableName: accounts
#        filePath: accounts.csv

works:
    work:
        time: 10
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench