type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 100
collect_pg_stat_statements: true
yaml_version: v1.0
use_dist_in_explain: true
works:
    work:
        time_secs: 300
        rate: unlimited
        warmup: 5
        active_terminals: 100
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table IF EXISTS user_events1;
            - drop table IF EXISTS user_events2;
            - drop table IF EXISTS user_events3;
            - drop table IF EXISTS user_events4;
            - CREATE TABLE user_events1 (
                event_id UUID,
                user_id INT NOT NULL,
                event_time TIMESTAMP NOT NULL,
                is_active BOOLEAN NOT NULL,
                event_type TEXT NOT NULL,
                details TEXT,
                priority INT,
                session_id UUID,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP,
                PRIMARY KEY(event_id asc));
            - CREATE INDEX idx_1_user_id ON user_events1(user_id asc);
            - CREATE INDEX idx_1_event_time ON user_events1(event_time asc);
            - CREATE INDEX idx_1_is_active ON user_events1(session_id asc);
            - CREATE INDEX idx_1_event_type ON user_events1(event_type asc);
            - CREATE TABLE user_events2 (
                event_id UUID,
                user_id INT NOT NULL,
                event_time TIMESTAMP NOT NULL,
                is_active BOOLEAN NOT NULL,
                event_type TEXT NOT NULL,
                details TEXT,
                priority INT,
                session_id UUID,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP,
                PRIMARY KEY(event_id asc));
            - CREATE INDEX idx_2_user_id ON user_events2(user_id asc);
            - CREATE INDEX idx_2_event_time ON user_events2(event_time asc);
            - CREATE INDEX idx_2_is_active ON user_events2(session_id asc);
            - CREATE INDEX idx_2_event_type ON user_events2(event_type asc);
            - CREATE TABLE user_events3 (
                event_id UUID,
                user_id INT NOT NULL,
                event_time TIMESTAMP NOT NULL,
                is_active BOOLEAN NOT NULL,
                event_type TEXT NOT NULL,
                details TEXT,
                priority INT,
                session_id UUID,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP,
                PRIMARY KEY(event_id asc));
            - CREATE INDEX idx_3_user_id ON user_events3(user_id asc);
            - CREATE INDEX idx_3_event_time ON user_events3(event_time asc);
            - CREATE INDEX idx_3_is_active ON user_events3(session_id asc);
            - CREATE INDEX idx_3_event_type ON user_events3(event_type asc);
            - CREATE TABLE user_events4 (
                event_id UUID,
                user_id INT NOT NULL,
                event_time TIMESTAMP NOT NULL,
                is_active BOOLEAN NOT NULL,
                event_type TEXT NOT NULL,
                details TEXT,
                priority INT,
                session_id UUID,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP,
                PRIMARY KEY(event_id asc));
            - CREATE INDEX idx_4_user_id ON user_events4(user_id asc);
            - CREATE INDEX idx_4_event_time ON user_events4(event_time asc);
            - CREATE INDEX idx_4_is_active ON user_events4(session_id asc);
            - CREATE INDEX idx_4_event_type ON user_events4(event_type asc);
        executeRules:
            - workload: insert_events
              run:
                - name: insert_user_events1
                  weight: 25
                  queries:
                    - query: INSERT INTO user_events1 (event_id, user_id, event_time, is_active, event_type, details, priority, session_id, created_at, updated_at)
                             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
                      bindings:
                        - util: RandomUUID
                          params: []
                        - util: PrimaryIntGen
                          params: [2, 10000001]
                        - util: RandomTimestamp
                          params: [100000]
                        - util: RandomBoolean
                          params: []
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: RandomInt
                          params: [1, 10]
                        - util: RandomUUID
                          params: []
                        - util: RandomTimestamp
                          params: [10000000]
                        - util: RandomTimestamp
                          params: [10000000]
                - name: insert_user_events2
                  weight: 25
                  queries:
                    - query: INSERT INTO user_events2 (event_id, user_id, event_time, is_active, event_type, details, priority, session_id, created_at, updated_at)
                             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
                      bindings:
                        - util: RandomUUID
                          params: []
                        - util: PrimaryIntGen
                          params: [2, 10000001]
                        - util: RandomTimestamp
                          params: [100000]
                        - util: RandomBoolean
                          params: []
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: RandomInt
                          params: [1, 10]
                        - util: RandomUUID
                          params: []
                        - util: RandomTimestamp
                          params: [10000000]
                        - util: RandomTimestamp
                          params: [10000000]
                - name: insert_user_events3
                  weight: 25
                  queries:
                    - query: INSERT INTO user_events3 (event_id, user_id, event_time, is_active, event_type, details, priority, session_id, created_at, updated_at)
                             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
                      bindings:
                        - util: RandomUUID
                          params: []
                        - util: PrimaryIntGen
                          params: [2, 10000001]
                        - util: RandomTimestamp
                          params: [100000]
                        - util: RandomBoolean
                          params: []
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: RandomInt
                          params: [1, 10]
                        - util: RandomUUID
                          params: []
                        - util: RandomTimestamp
                          params: [10000000]
                        - util: RandomTimestamp
                          params: [10000000]
                - name: insert_user_events4
                  weight: 25
                  queries:
                    - query: INSERT INTO user_events4 (event_id, user_id, event_time, is_active, event_type, details, priority, session_id, created_at, updated_at)
                             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
                      bindings:
                        - util: RandomUUID
                          params: []
                        - util: PrimaryIntGen
                          params: [2, 10000001]
                        - util: RandomTimestamp
                          params: [100000]
                        - util: RandomBoolean
                          params: []
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: OneStringFromArray
                          params: [['Login', 'Purchase', 'Logout', 'ProfileUpdate', 'PasswordReset']]
                        - util: RandomInt
                          params: [1, 10]
                        - util: RandomUUID
                          params: []
                        - util: RandomTimestamp
                          params: [10000000]
                        - util: RandomTimestamp
                          params: [10000000]
