type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: true
loaderthreads: 1
terminals: 1
works:
    work:
        time_secs: 10
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal3
    properties:
        # Goal3 - 1 :: create table with 15 fields -> load data for 3M rows (only PK)
        tableName: orders
        columns: 15
        rows: 3000000
        filePath: orders.csv
        stringLength: 32

#        # Goal3 - 2 :: create table with 15 fields -> load data for 30M rows (only PK)
#        tableName: orders
#        columns: 15
#        rows: 30000000
#        filePath: orders.csv
#        stringLength: 32
#
#        # Goal3 - 3 :: create table with 15 fields -> load data for 300M rows (only PK)
#        tableName: orders
#        columns: 15
#        rows: 300000000
#        filePath: orders.csv
#        stringLength: 32
